# Generated by Django 2.0.7 on 2020-12-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_profissional', '0003_remove_usuario_profissional_data_criacao'),
        ('usuario_paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissionais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario_profissional.Usuario_profissional')),
            ],
        ),
    ]
