# Generated by Django 2.0.7 on 2020-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_paciente', '0002_profissionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
